# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@7.5.5", "@babel/code-frame@^7.0.0", "@babel/code-frame@^7.5.5":
  version "7.5.5"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.5.5.tgz#bc0782f6d69f7b7d49531219699b988f669a8f9d"
  dependencies:
    "@babel/highlight" "^7.0.0"

"@babel/core@7.6.0", "@babel/core@^7.1.0", "@babel/core@^7.4.5":
  version "7.6.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.6.0.tgz#9b00f73554edd67bebc86df8303ef678be3d7b48"
  dependencies:
    "@babel/code-frame" "^7.5.5"
    "@babel/generator" "^7.6.0"
    "@babel/helpers" "^7.6.0"
    "@babel/parser" "^7.6.0"
    "@babel/template" "^7.6.0"
    "@babel/traverse" "^7.6.0"
    "@babel/types" "^7.6.0"
    convert-source-map "^1.1.0"
    debug "^4.1.0"
    json5 "^2.1.0"
    lodash "^4.17.13"
    resolve "^1.3.2"
    semver "^5.4.1"
    source-map "^0.5.0"
